### ISSUE TITLE
검색 / 확인 시 검색 결과 뷰가 나오도록 설정

### ISSUE THREAD

**Issue by empty005** [gambler-iOS/gambler#35]

**Comment by empty005** [comment]
검색 / 확인 버튼을 넣는게 나을지? 아니면 어떻게 처리를 해야 할지 고민입니다,

**Comment by da-hye0** [comment]
> 검색 / 확인 버튼을 넣는게 나을지? 아니면 어떻게 처리를 해야 할지 고민입니다,

저는 없는게 조아요~~~~!
