### ISSUE TITLE
질문: 내 주변 매장의 범위는 얼마정도가 좋을까요?

### ISSUE THREAD

**Issue by da-hye0** [gambler-iOS/gambler#44]
### 지도
범위 내부에 있는 데이터만 시트에 전달 할 예정인데
네이버 지도랑 카맵은 1.5km 이내로 보입니다.

저희는 몇 km정도로 하면 좋을까요?!

**Comment by empty005** [comment]
기본 지도의 설정시에 카메라 비율이 어느 정도로 될까요?
(ex, 1: 500과 같은 축척 값 설정을 알고 나서 휴대전화 크기에 맞추면 좋을 듯 싶습니다.)

**Comment by da-hye0** [comment]
회의 후 1km로 결정, 추후에 이상하면 변경
