### ISSUE TITLE
Review - 이미지 취소 버튼 질문드립니다.

### ISSUE THREAD

**Issue by parkinghun** [gambler-iOS/gambler#53]
참고) #46 

“searchClosed" 이미지를 사진의 취소 버튼으로 만들 때 foregroundStyle(Color.primaryDefault) 로 변경하면 아래 사진처럼 변경되어 적용이 어려울 것 같습니다.
채영님께 새로운 이미지를 받아서 적용하는게 좋을까요?

<img width="94" alt="image" src="https://github.com/gambler-iOS/gambler/assets/114156413/18c8ffb6-32f1-4515-95d9-b57b2aa41731">

<img width="220" alt="image" src="https://github.com/gambler-iOS/gambler/assets/114156413/1a689cea-addd-4558-915e-e446fff61cef">

**Comment by da-hye0** [comment]
좋습니다~

**Comment by empty005** [comment]
넵!! 안되면 적용해야지요,,!

**Comment by parkinghun** [comment]
아래와 같은 코드로 진행했습니다.
Image("searchClosed")
                                    .renderingMode(.template)
                                    .resizable()
                                    .frame(width: 24, height: 24)
                                    .foregroundStyle(Color.primaryDefault)

채영님이 피그마에 색 변경 없이 기본 이미지로 진행올려주셨는데 색상 변경 없이 진행할까요?
<img width="470" alt="image" src="https://github.com/gambler-iOS/gambler/assets/114156413/01704cf3-96f0-4a29-abde-478ae00c0a36">

**Comment by parkinghun** [comment]
해결 - 피그마에서 해당 버튼의 색상을 Primary/Default로 변경 후 asset에 추가하여 적용하였습니다.
