### ISSUE TITLE
모델 전체적으로 정검 및 수정

### ISSUE THREAD

**Issue by licors** [gambler-iOS/gambler#59]
## Feature
회의에서 모델 전체적으로 정검 및 수정

## Description
모델 수정하고 컴파일 에러 수정

Todo
- [x] AgreeTerms
- [x] Complain
- [x] EventBanner
- [x] Game
- [x] Notice
- [x] Report
- [x] Review
- [x] SearchKeyword
- [x] Shop
- [x] User

삭제
- [x] SearchHistory 

ETC
기타사항 없음

**Comment by da-hye0** [comment]
^0^ 라벨 다같이 있는거 넘 귀엽네요ㅎ0ㅎ0ㅎㅎ
(여기 이런말 써도돼여..?)

**Comment by licors** [comment]
ㅋㅋㅋ 낙서장? 이니 괜찮지 않을까요? 하지만 완료되어 현재 이슈 닫도록 하겠습니다 ㅎㅎ
