### ISSUE TITLE
Review 작성 시 game.reviewCount 와 game.reviewRatingAverage 업데이트 하는 코드 구현

### ISSUE THREAD

**Issue by licors** [gambler-iOS/gambler#91]
@parkinghun 님께서 Review model 변경 예정이라고 하셔서 다음 이슈로 넘김

- [x] 코드 구현

**Comment by parkinghun** [comment]
enum ReviewCategory: Codable {
    case shop
    case game
    
    var path: String {
        switch self {
        case .shop:
            return "Shops"
        case .game:
            return "Games"
        }
    }
}

struct Review: AvailableFirebase, Hashable {
    var id: String
    let postId: String  // Shop / Game ID
    let userId: String
    var reviewContent: String
    var reviewRating: Double
    var reviewImage: [String]?
    let createdDate: Date
    let category: ReviewCategory  // 추가사항
